using Oxide.Ext.Discord.Exceptions;

public class PromiseCancelledException : BaseDiscordException
{
	internal PromiseCancelledException(string message)
		: base(message)
	{
	}
}
